---
namespace: "tcharl"
name: "ansible_orchestration_cli"
version: "1.0.1"
description: "Reuses the marvelous geerlingguy's Kubernetes role with some platform's compliant configuration"

authors:
  - "Charlie Mordant <cmordant1@gmail.com>"

repository: "https://github.com/OsgiliathEnterprise/ansible-orchestration-csi"
documentation: "https://github.com/OsgiliathEnterprise/ansible-orchestration-csi/blob/master/README.md"
homepage: "https://github.com/OsgiliathEnterprise/ansible-orchestration-csi"
issues: "https://github.com/OsgiliathEnterprise/ansible-orchestration-csi/issues"

readme: "README.md"
license:
  - "Apache-2.0"
tags:
  - "kubernetes"
  - "helm"
  - "cloud"
