---

- name: Helm-install | Create temporary directory to checkout git
  ansible.builtin.tempfile:
    state: directory
    suffix: orchestration-cli
  register: temp_orchestration_cli_directory

- name: Helm-install | download the helm release
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
    dest: "{{ temp_orchestration_cli_directory.path }}/helm-installer.sh"
    mode: '0700'

- name: Helm-install | install the helm release
  ansible.builtin.command: "{{ temp_orchestration_cli_directory.path }}/helm-installer.sh"
  register: installhelmdout
  changed_when: "'helm installed' in installhelmdout.stdout"
  args:
    chdir: "{{ temp_orchestration_cli_directory.path }}"
