---

- name: Kube-apply | execute descriptor {{ descriptor.path }}
  kubernetes.core.k8s:
    state: present
    src: "{{ temp_orchestration_cli_descriptor_directory.path }}/{{ descriptor_set.url | split('/') | last | split('.') | first }}/{{ descriptor.path }}"
    ca_cert: "{{ kube_cacert_path | default(omit) }}"
    client_cert: "{{ kube_sysadmin_client_cert_path | default(omit) }}"
    client_key: "{{ kube_sysadmin_client_key_path | default(omit) }}"
    kubeconfig: "{{ kube_config_path }}"
    namespace: "{{ descriptor.namespace | default(omit) }}"
    context: "{{ kube_context | default('kubernetes-admin@kubernetes') }}"
  register: res
  until: not res.failed
  retries: 10
  delay: 10
  become: true
