---

- name: Kube-master-tasks | check if should install helm
  ansible.builtin.include_tasks: helm-install.yml

- name: Kube-master-tasks | Create temporary directory to download kustomize
  ansible.builtin.tempfile:
    state: directory
    suffix: orchestration-cli_kustomize
  register: temp_orchestration_cli_kustomize_directory

- name: Kube-master-tasks | download the helm release
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh
    dest: "{{ temp_orchestration_cli_kustomize_directory.path }}/install_kustomize.sh"
    mode: '0700'

- name: Kube-master-tasks | Install Kustomize
  ansible.builtin.command: "{{ temp_orchestration_cli_kustomize_directory.path }}/install_kustomize.sh"
  args:
    chdir: /usr/bin
    creates: /usr/bin/kustomize
  become: True

- name: Kube-master-tasks | loop over git repos to download
  ansible.builtin.include_tasks: descriptor-set.yml
  loop: "{{ descriptor_sets }}"
  loop_control:
    loop_var: descriptor_set
  when:
   - descriptor_sets is defined
   - descriptor_sets | length > 0
