---

- name: Kube-master-tasks | check if should install helm
  ansible.builtin.include_tasks: helm-install.yml

- name: Kube-master-tasks | loop over git repos to download
  ansible.builtin.include_tasks: descriptor-set.yml
  loop: "{{ descriptor_sets }}"
  loop_control:
    loop_var: descriptor_set
  when:
   - descriptor_sets is defined
   - descriptor_sets | length > 0
