---
- name: Include orchestration role
  ansible.builtin.include_tasks: requirements.yml
  when:
   - standalone_role
  tags:
    - standalone

- name: Import dependencies
  ansible.builtin.import_tasks: prereq.yml
  when:
   - kube_masters_group in group_names

- name: Include kube master operations
  ansible.builtin.include_tasks: kube-master-tasks.yml
  when: >
    kube_masters_group in group_names or
    (skip_master_check is defined and skip_master_check)
