---
- name: ansible-orchestration-cli | include orchestration role
  ansible.builtin.include_tasks: requirements.yml
  when:
   - standalone_role
   - kube_masters_group in group_names
  tags:
    - standalone

- name: ansible-orchestration-cli | include kube master operations
  ansible.builtin.include_tasks: kube-master-tasks.yml
  when: >
    kube_masters_group in group_names or
    (skip_master_check is defined and skip_master_check)
