---
- name: Prepare IDM server
  hosts:
    - idm.osgiliath.test
  tasks:
    - name: "install fedora ansible prerequisites"
      ansible.builtin.raw: dnf install -y python3 python3-libdnf5
      changed_when: false
      become: true
    - include_role:
        name: tcharl.freeipa_server
      vars:
        secure_logs: False
        preferred_nic: "eth1"
        idm_preferred_nic: "eth1"
        master_preferred_nic: "eth1"
        company_domain: osgiliath.test
        company_realm_password: '123ADMin'
        company_ad_password: '123ADmPass'

- name: Prepare
  hosts:
    - master.osgiliath.test
    - node1.osgiliath.test
  tasks:
    - name: "install fedora ansible prerequisites"
      ansible.builtin.raw: dnf install -y python3 python3-libdnf5
      changed_when: false
      become: true
    - include_role:
        name: tcharl.ansible_orchestration_cli
        tasks_from: requirements.yml
      vars:
        secure_logs: False
        preferred_nic: "eth1"
        idm_preferred_nic: "eth1"
        master_preferred_nic: "eth1"
        kube_firewall_zone: 'public'
        company_domain: osgiliath.test
        company_realm_password: '123ADMin'
        company_ad_password: '123ADmPass'
        nfs_mountpoints:
          - host: master.osgiliath.test
            mountpoints:
              - local: /net
                expose_kube_volume: True
                mountsize: 1
