---
dependency:
  name: galaxy
  enabled: ${DEPENDENCY_ENABLED:-True}
  options:
    role-file: ${REQUIREMENTS_PATH:-requirements-standalone.yml}
    roles-path: ${MOLECULE_PROJECT_DIRECTORY}/../community
    requirements-file: requirements-collections.yml
    collections-path: ${MOLECULE_PROJECT_DIRECTORY}/../community-collections
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: master.osgiliath.test
    box: ${TESTBOX:-fedora/38-cloud-base}
    provider_options:
      driver: "kvm"
      cpus: 4
      memory: 8096
    interfaces:
      - auto_config: true
        network_name: private_network
        ip: "192.168.50.4"
    groups:
      - kube_master
      - kube_node
      - ipaservers
provisioner:
  name: ansible
#  config_options:
#    defaults:
#      forks: 20
#   ssh_connection:
#     pipelining: true
#      ssh_args: -o ControlMaster=auto -o ControlPersist=6000s
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  options:
    v: 1
scenario:
  name: kvm
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
 #   - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
