---
# TODO This phase fails once

- name: Prepare IDM
  hosts:
    - idm.osgiliath.test
  tasks:
    - name: "install fedora ansible prerequisites"
      ansible.builtin.raw: dnf install -y python3 python3-libdnf5
      changed_when: false
      become: true
    - include_role:
        name: tcharl.freeipa_server
      vars:
        secure_logs: False
        preferred_nic: "eth1"
        idm_preferred_nic: "eth1"
        company_domain: osgiliath.test
        company_realm_password: '123ADMin'
        company_ad_password: '123ADmPass'
    - include_role:
        name: tcharl.ansible_nameserver
      vars:
        standalone_role: False
        secure_logs: False
        preferred_nic: "eth1"
        company_domain: osgiliath.test
        idm_preferred_nic: "eth1"
        company_realm_password: '123ADMin'
        company_ad_password: '123ADmPass'
- name: Prepare IPA clients
  hosts:
    - master.osgiliath.test
    - node1.osgiliath.test
  tasks:
    - name: "install fedora ansible prerequisites"
      ansible.builtin.raw: dnf install -y python3 python3-libdnf5
      changed_when: false
      become: true
    - include_role:
        name: tcharl.ansible_securehost
      vars:
        standalone_role: False
        secure_logs: False
        preferred_nic: "eth1"
        company_domain: osgiliath.test
        idm_preferred_nic: "eth1"
        company_realm_password: '123ADMin'
        company_ad_password: '123ADmPass'
    - include_role:
        name: tcharl.ansible_nameserver
      vars:
        standalone_role: False
        secure_logs: False
        preferred_nic: "eth1"
        company_domain: osgiliath.test
        idm_preferred_nic: "eth1"
        company_realm_password: '123ADMin'
        company_ad_password: '123ADmPass'
- name: Prepare NFS server on Master
  hosts:
    - master.osgiliath.test
  tasks:
    - include_role:
        name: tcharl.nfs_server
      vars:
        standalone_role: False
        secure_logs: False
        preferred_nic: "eth1"
        company_domain: osgiliath.test
        idm_preferred_nic: "eth1"
        company_realm_password: '123ADMin'
        company_ad_password: '123ADmPass'
- name: Prepare NFS client on Node
  hosts:
    - node1.osgiliath.test
  tasks:
    - include_role:
        name: tcharl.nfs_client
      vars:
        standalone_role: False
        secure_logs: False
        preferred_nic: "eth1"
        company_domain: osgiliath.test
        idm_preferred_nic: "eth1"
        company_realm_password: '123ADMin'
        company_ad_password: '123ADmPass'
- name: Prepare Kubernetes
  hosts:
    - master.osgiliath.test
    - node1.osgiliath.test
  tasks:
    - name: "install fedora ansible prerequisites"
      ansible.builtin.raw: dnf install -y python3 python3-libdnf5
      changed_when: false
      become: true
    - include_role:
        name: tcharl.ansible_orchestration
      vars:
        standalone_role: False
        secure_logs: False
        preferred_nic: "eth1"
        company_domain: osgiliath.test
        idm_preferred_nic: "eth1"
        master_preferred_nic: "eth1"
        company_realm_password: '123ADMin'
        company_ad_password: '123ADmPass'
